export const PHOTOS_FETCH_START = 'PHOTOS_FETCH_START';
export const PHOTOS_FETCH_SUCCESS = 'PHOTOS_FETCH_SUCCESS';
export const PHOTOS_FETCH_ERROR = 'PHOTOS_FETCH_ERROR';

export const FAVORITE_TOGGLE = 'FAVORITE_TOGGLE';
